### ISSUE TITLE
Add some screenshots

### ISSUE THREAD

**Issue by MadLittleMods** [TheWispy/Hacklight#7]
Would love to see some screenshots and see what how this looks without having to set it up myself.

**Comment by dannycjones** [comment]
Hi there - thank you for taking an interest in our project! 😄 

I've updated [README.md](https://github.com/TheWispy/Hacklight/blob/cd6590069c90f7fc8e9d6a95f28a121d6c82ccfd/README.md) with a gif and a little bit more information.
